name: flash_chat_test
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  intl: ^0.17.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  image: images/splash.png
  color: "#ffffff"
  fill: false

flutter:

  uses-material-design: true

  assets:
    - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
